name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/get-changed-files@v1
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: ''
      - uses: basedosdados/action-add-to-cloudtask@v1.4.7
        with:
          myInput: world